2005-02-09  Sebastien Pouliot  <sebastien@ximian.com>
	* cas1.cs: Changed for an easier to test case.
	* cas2-5: New. "Normal" LinkDemand test cases.
	* icall1.cs, icall2.cs: Updated to work on both Mono and MS runtime.
	* icall2-6.cs: New. More internal call test cases.
	* Makefile: Updated makefile.
	* pinvoke1-2.cs: Updated to work on both Mono and MS runtime.
	* pinvoke3-4.cs: New. More P/Invoke test cases.
	* README: Updated informations.


svn path=/trunk/mono/; revision=40359


Commit migrated from https://github.com/mono/mono/commit/ed2d0ac58fc9856bc65e1fdd16793d30d891fa24

diff --git a/src/mono/mono/tests/cas/linkdemand/Makefile b/src/mono/mono/tests/cas/linkdemand/Makefile
--- a/src/mono/mono/tests/cas/linkdemand/Makefile
+++ b/src/mono/mono/tests/cas/linkdemand/Makefile
@@ -2,17 +2,22 @@ RUNTIME = mono --debug --security
 CSCOMPILE = mcs --debug
 PROFILE = net_1_1
 
-all:	icall1a.exe icall1b.exe icall2a.exe icall2b.exe \
+all:	icall1.exe icall2.exe icall3.exe icall4.exe icall5.exe icall6.exe \
 	aptc1a.exe aptc1b.exe aptc2a.exe aptc2b.exe aptclib.dll \
-	pinvoke1.exe pinvoke2.exe cas1.exe 
+	pinvoke1.exe pinvoke2.exe pinvoke3.exe pinvoke4.exe \
+	cas1.exe cas2.exe cas3.exe cas4.exe cas5.exe
 
-aot:	icall1a.exe.so icall1b.exe.so icall2a.exe.so icall2b.exe.so \
+aot:	icall1.exe.so icall2.exe.so icall3.exe.so icall4.exe.so icall5.exe.so icall6.exe.so \
 	aptc1a.exe.so aptc1b.exe.so aptc2a.exe.so aptc2b.exe.so aptclib.dll.so \
-	pinvoke1.exe.so pinvoke2.exe.so cas1.exe.so
+	pinvoke1.exe.so pinvoke2.exe.so pinvoke3.exe.so pinvoke4.exe.so \
+	cas1.exe.so cas2.exe.so cas3.exe.so cas4.exe.so cas5.exe.so
 
-FULLTRUST_TEST_FILES = icall1a icall1b icall2a icall2b \
+FULLTRUST_TEST_FILES = icall1 icall2 icall3 icall4 icall5 icall6 \
 	aptc1a aptc1b aptc2a aptc2b \
-	pinvoke1 pinvoke2 cas1 
+	pinvoke1 pinvoke2 pinvoke4 \
+	cas1 cas3 cas4 cas5
+
+UNHANDLED_TEST_FILES = cas2 pinvoke3
 
 INTERNET_TEST_FILES = pinvoke1 pinvoke2 cas1
 
@@ -36,6 +41,17 @@ test: all
 			echo -e "fulltrust-$$i\tFAIL ($$?)";	\
 			failed=`expr $${failed} + 1`; \
 			failed_tests="$${failed_tests} fulltrust-$$i"; \
+		fi;	\
+	done;	\
+	for i in $(UNHANDLED_TEST_FILES); do	\
+		$(RUNTIME) $$i.exe > /dev/null;	\
+		if [ "$$?" = "0" ]; then	\
+			echo -e "unhandled-$$i\tFAIL ($$?)";	\
+			failed=`expr $${failed} + 1`; \
+			failed_tests="$${failed_tests} unhandled-$$i"; \
+		else	\
+			echo -e "unhandled-$$i\tpass";	\
+			passed=`expr $${passed} + 1`; \
 		fi;	\
 	done;	\
 #	for i in $(INTERNET_TEST_FILES); do	\
