2007-05-06  Rodrigo Kumpera  <kumpera@gmail.com>
	* Makefile (run-test): Make it use pedump instead of mono for validation
	* make_tests.sh: New tests
	* invalid_stack_2_tet.il: New test
	* make_ret_test.sh: New test script
	* make_load_test.sh: New test script
	* make_obj_store_test.sh: Test did not generate valid code for some cases
	* make_store_test.sh: Test did not generate valid code for some cases


svn path=/trunk/mono/; revision=78794


Commit migrated from https://github.com/mono/mono/commit/04f12466c35ad20c9f59651546902cfbdcb098eb

diff --git a/src/mono/mono/tests/verifier/Makefile b/src/mono/mono/tests/verifier/Makefile
--- a/src/mono/mono/tests/verifier/Makefile
+++ b/src/mono/mono/tests/verifier/Makefile
@@ -3,7 +3,7 @@
 	ilasm -out:$@ $<
 
 compile-stamp: generate-stamp
-	for i in *.il; do ilasm $$i; done
+	for i in *.il; do ilasm2 $$i; done
 	touch compile-stamp
 
 clean:
@@ -19,20 +19,27 @@ test: compile-stamp run-test
 
 run-test:
 	@for i in *.exe; do \
-		echo -n $$i; \
-		mono $$i >/dev/null 2>/dev/null; \
-		RES=$$?; \
-		if [ $$RES = 1 ]; \
+		#echo $$i; \
+		TEST=`echo $$i | cut -d '.' -f 1`; \
+		RES=99; \
+		FIRST=`echo $$i | cut -d '_' -f 1`; \
+		if [ "$$FIRST" == "invalid" ]; \
 		then \
-			echo " OK"; \
+			RES=3; \
 		fi; \
-		if [ $$RES = 0 ]; \
+		if [ "$$FIRST" == "unverifiable" ]; \
 		then \
-			echo " NOT OK (silent success)"; \
+			RES=2; \
 		fi; \
-		if [ $$RES '>' 1 ]; \
+		if [ "$$FIRST" == "valid" ]; \
 		then \
-			echo " NOT OK (other failure)"; \
+			RES=0; \
+		fi; \
+		../../metadata/pedump --verify error,warn,cls,code $$TEST.exe >/dev/null 2>/dev/null;\
+		R=$$?; \
+		if [ $$R != $$RES ]; \
+		then \
+			echo "$$TEST failed expected $$RES but got $$R"; \
 		fi; \
 	done
 
