2002-02-17  Radek Doulik  <rodo@ximian.com>
	* mono/tests/Makefile.am (test): display # of failed tests

svn path=/trunk/mono/; revision=2464


Commit migrated from https://github.com/mono/mono/commit/5bbb919c76ec3cec5a6650a42911986886d7e414

diff --git a/src/mono/mono/tests/Makefile.am b/src/mono/mono/tests/Makefile.am
--- a/src/mono/mono/tests/Makefile.am
+++ b/src/mono/mono/tests/Makefile.am
@@ -82,9 +82,14 @@ EXTRA_DIST=test-driver $(TESTSRC)
 	$(CSC) $<
 
 test: $(TEST_PROG) $(TESTSI)
+	@failed=0; \
 	for i in $(TESTSI); do	\
-		./test-driver $(TEST_PROG) $$i;	\
-	done
+		if ! ./test-driver $(TEST_PROG) $$i; \
+		then \
+			failed=`expr $${failed} + 1`; \
+		fi \
+	done; \
+	echo "$${failed} test(s) failed."
 
 testb: $(TEST_PROG) $(TESTBS)
 	for i in $(TESTBS); do	\
