Check for global dotnet-serve

diff --git a/src/mono/netcore/sample/wasm/browser/Makefile b/src/mono/netcore/sample/wasm/browser/Makefile
--- a/src/mono/netcore/sample/wasm/browser/Makefile
+++ b/src/mono/netcore/sample/wasm/browser/Makefile
@@ -18,4 +18,9 @@ clean:
 	rm -rf bin
 
 run:
-	$(DOTNET) serve -o -d bin/$(CONFIG)/publish -p 8000
+	if ! $(DOTNET) tool list --global | grep dotnet-serve; then \
+		echo "The tool dotnet-serve could not be found. Install with: $(DOTNET) tool install --global dotnet-serve"; \
+		exit 1; \
+	else  \
+		$(DOTNET) serve -d bin/$(CONFIG)/publish -p 8000; \
+	fi
