[netcore][llvm] Implement Sse1-4.2 subsets used by corlib (mono/mono#18103)
* Implement SSE41 subset used by corlib

* Implement Sse2.MoveMask

* only works with llvm

* Implement Sse3 and Ssse3 subsets used by corlib

* Implement a few SSE1 methods

* Address feedback, also, implement Sse.Add/Subtract

* Fix build

* Implement Sse.Multiply, Sse.Store

* Implement Sse.CompareNotEquals

* Implement Sse.MoveScalar

* Finish SSE1 corlib subset

* Implement Sse.LoadVector128, Sse.Shuffle

* Sse.Shuffle cleanup

* Implement Sse2 APIs

* More of SSE2: LoadAlignedVector128, Compare*

* Implement Sse2.Unpack* and Sse2.StoreScalar

* Implement Sse2.PackUnsignedSaturate

* Implement Sse2.ShiftRightLogical

* Implement Sse2.Shuffle

* Implement Vector128<T>.Zero

* Fix CreateScalarUnsafe

* Implement Vector128.As*, Fix Vector128.CreateScalarUnsafe

* Fix failures

* Fix failures

* Fix Sse.MoveMask

* remove redundant null checks

* Fix AOT failures

* fix compilation warrning

* rename create_vector_mask_*

* Fix failures found via tests

* Index in Sse41.Insert has to be a constant

* add local tests for mono

* Update tests (cleanup)

* Code cleanup

* test

* fix typo

* Clean up

* Clean up

* Implement And, AndNot, Or, Xor, Divide for Sse1

* Cleanup

* Fix build

* limit emit_vector128 with LLVM

* enable IsSupported for corlib

* Fix build on wasm (if-defs issue)

* Don't intrinsify Vector256

* Address feedback


Commit migrated from https://github.com/mono/mono/commit/423192ed85c0b2263b46f3f4cfa63ec7b90b3f31

diff --git a/src/mono/netcore/Makefile b/src/mono/netcore/Makefile
--- a/src/mono/netcore/Makefile
+++ b/src/mono/netcore/Makefile
@@ -274,6 +274,28 @@ run-tests-coreclr: prepare update-tests-coreclr corerun
 	echo "Failed: $$failures"
 endif
 
+run-tests-mono: prepare
+	failures=0; \
+	counter=0; \
+	test_prj_dir=''; \
+	test_prj_name=''; \
+	test_projects=$$(find tests -type f -name "*.csproj"); \
+	for test_prj in $$test_projects; do \
+		counter=$$((counter+1)); \
+		echo "Running $$test_prj_dir"; \
+		test_prj_dir=$$(dirname $$test_prj); \
+		test_prj_name=$$(basename $$test_prj); \
+		test_prj_name=$${test_prj_name%.*}; \
+		$(DOTNET) build -c Release $$test_prj; \
+		MONO_ENV_OPTIONS="--debug $(MONO_ENV_OPTIONS)" COMPlus_DebugWriteToStdErr=1 ./dotnet --fx-version "$(NETCOREAPP_VERSION)" $$test_prj_dir/bin/netcoreapp3.0/$$test_prj_name.dll; \
+		if [ $$? -ne 0 ]; then \
+			failures=$$((failures+1)); \
+		fi; \
+	done; \
+	echo "======================"; \
+	echo "Tests Count: $$counter"; \
+	echo "Failed: $$failures"
+
 run-tests-coreclr-%: prepare update-tests-coreclr
 	@echo ""
 	@echo "***************** $* *********************"
