2009-01-09 Rodrigo Kumpera  <rkumpera@novell.com>
	* Makefile: Add check_with_peverify target to make it easier to
	check against MS peverify.

svn path=/trunk/mono/; revision=123054


Commit migrated from https://github.com/mono/mono/commit/57e2b11047a6fb883914ec81c1b288ba403b803d

diff --git a/src/mono/mono/tests/metadata-verifier/Makefile b/src/mono/mono/tests/metadata-verifier/Makefile
--- a/src/mono/mono/tests/metadata-verifier/Makefile
+++ b/src/mono/mono/tests/metadata-verifier/Makefile
@@ -13,3 +13,22 @@ header-tests.ok: header-tests.md simple-assembly.exe
 
 generate_stamp: header-tests.ok
 	touch generate-stamp
+
+check_with_peverify: generate_stamp
+	@for i in *.exe; do \
+		RES=99; \
+		FIRST=`echo $$i | cut -d '-' -f 1`; \
+		if [ "$$FIRST" == "invalid" ];	then \
+			RES=1; \
+		fi; \
+		if [ "$$FIRST" == "valid" ]; then \
+			RES=0; \
+		fi; \
+		if [ $$RES != 99 ]; then \
+			peverify $$i >/dev/null 2>/dev/null; \
+			R=$$?; \
+			if [ $$R != $$RES ]; then \
+				echo "$$i failed expected $$RES but got $$R"; \
+			fi; \
+		fi; \
+	done
